### ISSUE TITLE
Compatibility with Angular 7

### ISSUE THREAD

**Issue by PavelGolodoniuc** [zainzafar90/angular-switchery-ios#1]
Package "angular-switchery-ios" has an incompatible peer dependency to "rxjs" (requires "^5.1.0", would install "6.3.3").
Package "angular-switchery-ios" has an incompatible peer dependency to "@angular/core" (requires ">=5.0.0-rc.0 <6.0.0||>=4.0.0 <5.0.0", would install "7.2.2").
Incompatible peer dependencies found. See above.

**Comment by zainzafar90** [comment]
Working on it and making it compatible for Angular 7

**Comment by PavelGolodoniuc** [comment]
I'll check it next week... Ta
