### ISSUE TITLE
[(ngModel)] Doesn't seem to work with angular 8

### ISSUE THREAD

**Issue by mjarkk** [zainzafar90/angular-switchery-ios#2]
I'v added the following code:
```html
<ng-switchery [(ngModel)]="value"></ng-switchery>
<p>{{value}}</p>
```
But when i click the switch it doesn't update the value, do you have any idea why this is happening.

**Comment by kanup** [comment]
It works for me on angular 8.2.11.

May be you haven't imported FormsModule.

**Comment by mjarkk** [comment]
I had already switched to another library and can't look at the code anymore.  
If you say it works fine in angular 8 i'll close this issue and might open it again in the further if it comes up again.
