### ISSUE TITLE
Interactive 'moving-part' of switch is appearing too high on load

### ISSUE THREAD

**Issue by HarryCarron** [zainzafar90/angular-switchery-ios#3]
<img width="211" alt="Screenshot 2020-03-11 at 20 52 55" src="https://user-images.githubusercontent.com/22551551/76463011-94482d80-63da-11ea-8da5-fda28ca9ab9b.png">

_Possibly due to using 'switchery-xs' size_
**see screenshot attached** On initial load, the moving-part of the component is appearing a few pixels too high off central alignment. After interacting with the component it realigns.

**See second screenshot**
<img width="202" alt="Screenshot 2020-03-11 at 20 53 03" src="https://user-images.githubusercontent.com/22551551/76463236-f7d25b00-63da-11ea-9a2f-463e70f0d193.png">

**Comment by kanup** [comment]
switchery-xs is working fine on the demo. Could be your other elements or css interacting with the switch?
